### ISSUE TITLE
"ls" of non-existent key ("path") should return non-zero error code from tool for shell scriptures

### ISSUE THREAD

**Issue by Brent-Knight-BL** [rholder/esthree#18]
Long time listener, first time caller, here ...

I am currently working-around this easily enough by checking for an empty stdout.

Here's the behavior I'd like it to emulate:

```
$ ls filename-that-does-not-exist ; echo $?
ls: filename-that-does-not-exist: No such file or directory
1
```

And here's what `esthree` does:

```
$ esthree ls s3:/my-bucket-name/filename-that-does-not-exist ; echo $?

0
```

To be clear, I don't care about the error message (which may be printed to stdout or stderr, I don't care) ... I only care about the return code.

Apologies that this isn't a pull request ... :(

But I just wanted to record this nit somewhere.

**Comment by rholder** [comment]
`s3cmd` also appears to behave the same way returning 0.

**Comment by Brent-Knight-BL** [comment]
Curses

**Comment by rholder** [comment]
A list call to an S3 bucket that 1.) exists, and 2.) you have access to is the underlying reason. It wouldn't be an error to list an empty bucket, and I think that's what we're seeing here.

**Comment by Brent-Knight-BL** [comment]
Yes, makes perfect sense in that model.

**Comment by rholder** [comment]
This turned out to be a non-bug.
